//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class ChebiWebServiceFault
    {
        
        private string faultInfoField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faultInfo
        {
            get
            {
                return this.faultInfoField;
            }
            set
            {
                this.faultInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class LiteEntity
    {
        
        private string chebiIdField;
        
        private string chebiAsciiNameField;
        
        private float searchScoreField;
        
        private bool searchScoreFieldSpecified;
        
        private int entityStarField;
        
        private bool entityStarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string chebiAsciiName
        {
            get
            {
                return this.chebiAsciiNameField;
            }
            set
            {
                this.chebiAsciiNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float searchScore
        {
            get
            {
                return this.searchScoreField;
            }
            set
            {
                this.searchScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchScoreSpecified
        {
            get
            {
                return this.searchScoreFieldSpecified;
            }
            set
            {
                this.searchScoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int entityStar
        {
            get
            {
                return this.entityStarField;
            }
            set
            {
                this.entityStarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityStarSpecified
        {
            get
            {
                return this.entityStarFieldSpecified;
            }
            set
            {
                this.entityStarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getLiteEntityResponse
    {
        
        private LiteEntity[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public LiteEntity[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getLiteEntity
    {
        
        private string searchField;
        
        private SearchCategory searchCategoryField;
        
        private int maximumResultsField;
        
        private StarsCategory starsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string search
        {
            get
            {
                return this.searchField;
            }
            set
            {
                this.searchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SearchCategory searchCategory
        {
            get
            {
                return this.searchCategoryField;
            }
            set
            {
                this.searchCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int maximumResults
        {
            get
            {
                return this.maximumResultsField;
            }
            set
            {
                this.maximumResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StarsCategory stars
        {
            get
            {
                return this.starsField;
            }
            set
            {
                this.starsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum SearchCategory
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHEBI ID")]
        CHEBIID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHEBI NAME")]
        CHEBINAME,
        
        /// <remarks/>
        DEFINITION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ALL NAMES")]
        ALLNAMES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IUPAC NAME")]
        IUPACNAME,
        
        /// <remarks/>
        CITATIONS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("REGISTRY NUMBERS")]
        REGISTRYNUMBERS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MANUAL XREFS")]
        MANUALXREFS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AUTOMATIC XREFS")]
        AUTOMATICXREFS,
        
        /// <remarks/>
        FORMULA,
        
        /// <remarks/>
        MASS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MONOISOTOPIC MASS")]
        MONOISOTOPICMASS,
        
        /// <remarks/>
        CHARGE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INCHI/INCHI KEY")]
        INCHIINCHIKEY,
        
        /// <remarks/>
        SMILES,
        
        /// <remarks/>
        SPECIES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StarsCategory
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TWO ONLY")]
        TWOONLY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THREE ONLY")]
        THREEONLY,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", ConfigurationName="ServiceReference1.ChebiWebServicePortType")]
    public interface ChebiWebServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> getLiteEntityAsync(ServiceReference1.getLiteEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityResponse1> getCompleteEntityAsync(ServiceReference1.getCompleteEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityByListResponse> getCompleteEntityByListAsync(ServiceReference1.getCompleteEntityByListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getOntologyParentsResponse1> getOntologyParentsAsync(ServiceReference1.getOntologyParentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getOntologyChildrenResponse1> getOntologyChildrenAsync(ServiceReference1.getOntologyChildrenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> getAllOntologyChildrenInPathAsync(ServiceReference1.getAllOntologyChildrenInPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getStructureSearchResponse> getStructureSearchAsync(ServiceReference1.getStructureSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ChebiWebServiceFault), Action="", Name="ChebiWebServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getUpdatedPolymerResponse1> getUpdatedPolymerAsync(ServiceReference1.getUpdatedPolymerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiteEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getLiteEntity getLiteEntity;
        
        public getLiteEntityRequest()
        {
        }
        
        public getLiteEntityRequest(ServiceReference1.getLiteEntity getLiteEntity)
        {
            this.getLiteEntity = getLiteEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiteEntityResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getLiteEntityResponse getLiteEntityResponse;
        
        public getLiteEntityResponse1()
        {
        }
        
        public getLiteEntityResponse1(ServiceReference1.getLiteEntityResponse getLiteEntityResponse)
        {
            this.getLiteEntityResponse = getLiteEntityResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getCompleteEntity
    {
        
        private string chebiIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getCompleteEntityResponse
    {
        
        private Entity returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Entity @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class Entity
    {
        
        private string chebiIdField;
        
        private string chebiAsciiNameField;
        
        private string definitionField;
        
        private string statusField;
        
        private string smilesField;
        
        private string inchiField;
        
        private string inchiKeyField;
        
        private string chargeField;
        
        private string massField;
        
        private string monoisotopicMassField;
        
        private int entityStarField;
        
        private bool entityStarFieldSpecified;
        
        private string[] secondaryChEBIIdsField;
        
        private DataItem[] synonymsField;
        
        private DataItem[] iupacNamesField;
        
        private DataItem[] formulaeField;
        
        private DataItem[] registryNumbersField;
        
        private DataItem[] citationsField;
        
        private StructureDataItem[] chemicalStructuresField;
        
        private DataItem[] databaseLinksField;
        
        private OntologyDataItem[] ontologyParentsField;
        
        private OntologyDataItem[] ontologyChildrenField;
        
        private CommentDataItem[] generalCommentsField;
        
        private CompoundOriginDataItem[] compoundOriginsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string chebiAsciiName
        {
            get
            {
                return this.chebiAsciiNameField;
            }
            set
            {
                this.chebiAsciiNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string smiles
        {
            get
            {
                return this.smilesField;
            }
            set
            {
                this.smilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string inchi
        {
            get
            {
                return this.inchiField;
            }
            set
            {
                this.inchiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string inchiKey
        {
            get
            {
                return this.inchiKeyField;
            }
            set
            {
                this.inchiKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string charge
        {
            get
            {
                return this.chargeField;
            }
            set
            {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string mass
        {
            get
            {
                return this.massField;
            }
            set
            {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string monoisotopicMass
        {
            get
            {
                return this.monoisotopicMassField;
            }
            set
            {
                this.monoisotopicMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int entityStar
        {
            get
            {
                return this.entityStarField;
            }
            set
            {
                this.entityStarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityStarSpecified
        {
            get
            {
                return this.entityStarFieldSpecified;
            }
            set
            {
                this.entityStarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecondaryChEBIIds", Order=11)]
        public string[] SecondaryChEBIIds
        {
            get
            {
                return this.secondaryChEBIIdsField;
            }
            set
            {
                this.secondaryChEBIIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Synonyms", Order=12)]
        public DataItem[] Synonyms
        {
            get
            {
                return this.synonymsField;
            }
            set
            {
                this.synonymsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IupacNames", Order=13)]
        public DataItem[] IupacNames
        {
            get
            {
                return this.iupacNamesField;
            }
            set
            {
                this.iupacNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Formulae", Order=14)]
        public DataItem[] Formulae
        {
            get
            {
                return this.formulaeField;
            }
            set
            {
                this.formulaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryNumbers", Order=15)]
        public DataItem[] RegistryNumbers
        {
            get
            {
                return this.registryNumbersField;
            }
            set
            {
                this.registryNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Citations", Order=16)]
        public DataItem[] Citations
        {
            get
            {
                return this.citationsField;
            }
            set
            {
                this.citationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChemicalStructures", Order=17)]
        public StructureDataItem[] ChemicalStructures
        {
            get
            {
                return this.chemicalStructuresField;
            }
            set
            {
                this.chemicalStructuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatabaseLinks", Order=18)]
        public DataItem[] DatabaseLinks
        {
            get
            {
                return this.databaseLinksField;
            }
            set
            {
                this.databaseLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyParents", Order=19)]
        public OntologyDataItem[] OntologyParents
        {
            get
            {
                return this.ontologyParentsField;
            }
            set
            {
                this.ontologyParentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyChildren", Order=20)]
        public OntologyDataItem[] OntologyChildren
        {
            get
            {
                return this.ontologyChildrenField;
            }
            set
            {
                this.ontologyChildrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GeneralComments", Order=21)]
        public CommentDataItem[] GeneralComments
        {
            get
            {
                return this.generalCommentsField;
            }
            set
            {
                this.generalCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompoundOrigins", Order=22)]
        public CompoundOriginDataItem[] CompoundOrigins
        {
            get
            {
                return this.compoundOriginsField;
            }
            set
            {
                this.compoundOriginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class DataItem
    {
        
        private string dataField;
        
        private string typeField;
        
        private string sourceField;
        
        private CommentDataItem[] commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments", Order=3)]
        public CommentDataItem[] Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class CommentDataItem
    {
        
        private string textField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class StructureDataItem
    {
        
        private string structureField;
        
        private string typeField;
        
        private string dimensionField;
        
        private bool defaultStructureField;
        
        private bool defaultStructureFieldSpecified;
        
        private CommentDataItem[] commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string structure
        {
            get
            {
                return this.structureField;
            }
            set
            {
                this.structureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool defaultStructure
        {
            get
            {
                return this.defaultStructureField;
            }
            set
            {
                this.defaultStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultStructureSpecified
        {
            get
            {
                return this.defaultStructureFieldSpecified;
            }
            set
            {
                this.defaultStructureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments", Order=4)]
        public CommentDataItem[] Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class OntologyDataItem
    {
        
        private string chebiNameField;
        
        private string chebiIdField;
        
        private string typeField;
        
        private string statusField;
        
        private bool cyclicRelationshipField;
        
        private CommentDataItem[] commentsField;
        
        private OntologyDataItem[] ontologyElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiName
        {
            get
            {
                return this.chebiNameField;
            }
            set
            {
                this.chebiNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool cyclicRelationship
        {
            get
            {
                return this.cyclicRelationshipField;
            }
            set
            {
                this.cyclicRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments", Order=5)]
        public CommentDataItem[] Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyElement", Order=6)]
        public OntologyDataItem[] OntologyElement
        {
            get
            {
                return this.ontologyElementField;
            }
            set
            {
                this.ontologyElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class CompoundOriginDataItem
    {
        
        private string speciesTextField;
        
        private string speciesAccessionField;
        
        private string componentTextField;
        
        private string componentAccessionField;
        
        private string strainTextField;
        
        private string strainAccessionField;
        
        private string sourceTypeField;
        
        private string sourceAccessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string speciesText
        {
            get
            {
                return this.speciesTextField;
            }
            set
            {
                this.speciesTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string speciesAccession
        {
            get
            {
                return this.speciesAccessionField;
            }
            set
            {
                this.speciesAccessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string componentText
        {
            get
            {
                return this.componentTextField;
            }
            set
            {
                this.componentTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string componentAccession
        {
            get
            {
                return this.componentAccessionField;
            }
            set
            {
                this.componentAccessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string strainText
        {
            get
            {
                return this.strainTextField;
            }
            set
            {
                this.strainTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string strainAccession
        {
            get
            {
                return this.strainAccessionField;
            }
            set
            {
                this.strainAccessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SourceType
        {
            get
            {
                return this.sourceTypeField;
            }
            set
            {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SourceAccession
        {
            get
            {
                return this.sourceAccessionField;
            }
            set
            {
                this.sourceAccessionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompleteEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getCompleteEntity getCompleteEntity;
        
        public getCompleteEntityRequest()
        {
        }
        
        public getCompleteEntityRequest(ServiceReference1.getCompleteEntity getCompleteEntity)
        {
            this.getCompleteEntity = getCompleteEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompleteEntityResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getCompleteEntityResponse getCompleteEntityResponse;
        
        public getCompleteEntityResponse1()
        {
        }
        
        public getCompleteEntityResponse1(ServiceReference1.getCompleteEntityResponse getCompleteEntityResponse)
        {
            this.getCompleteEntityResponse = getCompleteEntityResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompleteEntityByListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ListOfChEBIIds", IsNullable=false)]
        public string[] getCompleteEntityByList;
        
        public getCompleteEntityByListRequest()
        {
        }
        
        public getCompleteEntityByListRequest(string[] getCompleteEntityByList)
        {
            this.getCompleteEntityByList = getCompleteEntityByList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompleteEntityByListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCompleteEntityByListResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", IsNullable=false)]
        public ServiceReference1.Entity[] getCompleteEntityByListResponse1;
        
        public getCompleteEntityByListResponse()
        {
        }
        
        public getCompleteEntityByListResponse(ServiceReference1.Entity[] getCompleteEntityByListResponse1)
        {
            this.getCompleteEntityByListResponse1 = getCompleteEntityByListResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyParents
    {
        
        private string chebiIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyParentsResponse
    {
        
        private OntologyDataItem[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public OntologyDataItem[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOntologyParentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getOntologyParents getOntologyParents;
        
        public getOntologyParentsRequest()
        {
        }
        
        public getOntologyParentsRequest(ServiceReference1.getOntologyParents getOntologyParents)
        {
            this.getOntologyParents = getOntologyParents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOntologyParentsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getOntologyParentsResponse getOntologyParentsResponse;
        
        public getOntologyParentsResponse1()
        {
        }
        
        public getOntologyParentsResponse1(ServiceReference1.getOntologyParentsResponse getOntologyParentsResponse)
        {
            this.getOntologyParentsResponse = getOntologyParentsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyChildren
    {
        
        private string chebiIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyChildrenResponse
    {
        
        private OntologyDataItem[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public OntologyDataItem[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOntologyChildrenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getOntologyChildren getOntologyChildren;
        
        public getOntologyChildrenRequest()
        {
        }
        
        public getOntologyChildrenRequest(ServiceReference1.getOntologyChildren getOntologyChildren)
        {
            this.getOntologyChildren = getOntologyChildren;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOntologyChildrenResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getOntologyChildrenResponse getOntologyChildrenResponse;
        
        public getOntologyChildrenResponse1()
        {
        }
        
        public getOntologyChildrenResponse1(ServiceReference1.getOntologyChildrenResponse getOntologyChildrenResponse)
        {
            this.getOntologyChildrenResponse = getOntologyChildrenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getAllOntologyChildrenInPath
    {
        
        private string chebiIdField;
        
        private RelationshipType relationshipTypeField;
        
        private bool structureOnlyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RelationshipType relationshipType
        {
            get
            {
                return this.relationshipTypeField;
            }
            set
            {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool structureOnly
        {
            get
            {
                return this.structureOnlyField;
            }
            set
            {
                this.structureOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum RelationshipType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a")]
        isa,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has part")]
        haspart,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is conjugate base of")]
        isconjugatebaseof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is conjugate acid of")]
        isconjugateacidof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is tautomer of")]
        istautomerof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is enantiomer of")]
        isenantiomerof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has functional parent")]
        hasfunctionalparent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has parent hydride")]
        hasparenthydride,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is substituent group from")]
        issubstituentgroupfrom,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has role")]
        hasrole,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllOntologyChildrenInPathRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getAllOntologyChildrenInPath getAllOntologyChildrenInPath;
        
        public getAllOntologyChildrenInPathRequest()
        {
        }
        
        public getAllOntologyChildrenInPathRequest(ServiceReference1.getAllOntologyChildrenInPath getAllOntologyChildrenInPath)
        {
            this.getAllOntologyChildrenInPath = getAllOntologyChildrenInPath;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getStructureSearch
    {
        
        private string structureField;
        
        private StructureType typeField;
        
        private StructureSearchCategory structureSearchCategoryField;
        
        private int totalResultsField;
        
        private float tanimotoCutoffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string structure
        {
            get
            {
                return this.structureField;
            }
            set
            {
                this.structureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StructureType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StructureSearchCategory structureSearchCategory
        {
            get
            {
                return this.structureSearchCategoryField;
            }
            set
            {
                this.structureSearchCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int totalResults
        {
            get
            {
                return this.totalResultsField;
            }
            set
            {
                this.totalResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float tanimotoCutoff
        {
            get
            {
                return this.tanimotoCutoffField;
            }
            set
            {
                this.tanimotoCutoffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StructureType
    {
        
        /// <remarks/>
        MOLFILE,
        
        /// <remarks/>
        CML,
        
        /// <remarks/>
        SMILES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StructureSearchCategory
    {
        
        /// <remarks/>
        IDENTITY,
        
        /// <remarks/>
        SUBSTRUCTURE,
        
        /// <remarks/>
        SIMILARITY,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStructureSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getStructureSearch getStructureSearch;
        
        public getStructureSearchRequest()
        {
        }
        
        public getStructureSearchRequest(ServiceReference1.getStructureSearch getStructureSearch)
        {
            this.getStructureSearch = getStructureSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStructureSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStructureSearchResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getLiteEntityResponse getStructureSearchResponse1;
        
        public getStructureSearchResponse()
        {
        }
        
        public getStructureSearchResponse(ServiceReference1.getLiteEntityResponse getStructureSearchResponse1)
        {
            this.getStructureSearchResponse1 = getStructureSearchResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getUpdatedPolymer
    {
        
        private string chebiIdField;
        
        private string[] polymerisationIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polymerisationIndex", Order=1)]
        public string[] polymerisationIndex
        {
            get
            {
                return this.polymerisationIndexField;
            }
            set
            {
                this.polymerisationIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getUpdatedPolymerResponse
    {
        
        private UpdatedPolymer returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UpdatedPolymer @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class UpdatedPolymer
    {
        
        private string updatedStructureField;
        
        private string globalFormulaField;
        
        private string globalChargeField;
        
        private string chebiIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string updatedStructure
        {
            get
            {
                return this.updatedStructureField;
            }
            set
            {
                this.updatedStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string globalFormula
        {
            get
            {
                return this.globalFormulaField;
            }
            set
            {
                this.globalFormulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string globalCharge
        {
            get
            {
                return this.globalChargeField;
            }
            set
            {
                this.globalChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string chebiId
        {
            get
            {
                return this.chebiIdField;
            }
            set
            {
                this.chebiIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedPolymerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getUpdatedPolymer getUpdatedPolymer;
        
        public getUpdatedPolymerRequest()
        {
        }
        
        public getUpdatedPolymerRequest(ServiceReference1.getUpdatedPolymer getUpdatedPolymer)
        {
            this.getUpdatedPolymer = getUpdatedPolymer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedPolymerResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi", Order=0)]
        public ServiceReference1.getUpdatedPolymerResponse getUpdatedPolymerResponse;
        
        public getUpdatedPolymerResponse1()
        {
        }
        
        public getUpdatedPolymerResponse1(ServiceReference1.getUpdatedPolymerResponse getUpdatedPolymerResponse)
        {
            this.getUpdatedPolymerResponse = getUpdatedPolymerResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ChebiWebServicePortTypeChannel : ServiceReference1.ChebiWebServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ChebiWebServicePortTypeClient : System.ServiceModel.ClientBase<ServiceReference1.ChebiWebServicePortType>, ServiceReference1.ChebiWebServicePortType
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ChebiWebServicePortTypeClient() : 
                base(ChebiWebServicePortTypeClient.GetDefaultBinding(), ChebiWebServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ChebiWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChebiWebServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ChebiWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), ChebiWebServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChebiWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ChebiWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChebiWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ChebiWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChebiWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> ServiceReference1.ChebiWebServicePortType.getLiteEntityAsync(ServiceReference1.getLiteEntityRequest request)
        {
            return base.Channel.getLiteEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> getLiteEntityAsync(ServiceReference1.getLiteEntity getLiteEntity)
        {
            ServiceReference1.getLiteEntityRequest inValue = new ServiceReference1.getLiteEntityRequest();
            inValue.getLiteEntity = getLiteEntity;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getLiteEntityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityResponse1> ServiceReference1.ChebiWebServicePortType.getCompleteEntityAsync(ServiceReference1.getCompleteEntityRequest request)
        {
            return base.Channel.getCompleteEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityResponse1> getCompleteEntityAsync(ServiceReference1.getCompleteEntity getCompleteEntity)
        {
            ServiceReference1.getCompleteEntityRequest inValue = new ServiceReference1.getCompleteEntityRequest();
            inValue.getCompleteEntity = getCompleteEntity;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getCompleteEntityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityByListResponse> ServiceReference1.ChebiWebServicePortType.getCompleteEntityByListAsync(ServiceReference1.getCompleteEntityByListRequest request)
        {
            return base.Channel.getCompleteEntityByListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getCompleteEntityByListResponse> getCompleteEntityByListAsync(string[] getCompleteEntityByList)
        {
            ServiceReference1.getCompleteEntityByListRequest inValue = new ServiceReference1.getCompleteEntityByListRequest();
            inValue.getCompleteEntityByList = getCompleteEntityByList;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getCompleteEntityByListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getOntologyParentsResponse1> ServiceReference1.ChebiWebServicePortType.getOntologyParentsAsync(ServiceReference1.getOntologyParentsRequest request)
        {
            return base.Channel.getOntologyParentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getOntologyParentsResponse1> getOntologyParentsAsync(ServiceReference1.getOntologyParents getOntologyParents)
        {
            ServiceReference1.getOntologyParentsRequest inValue = new ServiceReference1.getOntologyParentsRequest();
            inValue.getOntologyParents = getOntologyParents;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getOntologyParentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getOntologyChildrenResponse1> ServiceReference1.ChebiWebServicePortType.getOntologyChildrenAsync(ServiceReference1.getOntologyChildrenRequest request)
        {
            return base.Channel.getOntologyChildrenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getOntologyChildrenResponse1> getOntologyChildrenAsync(ServiceReference1.getOntologyChildren getOntologyChildren)
        {
            ServiceReference1.getOntologyChildrenRequest inValue = new ServiceReference1.getOntologyChildrenRequest();
            inValue.getOntologyChildren = getOntologyChildren;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getOntologyChildrenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> ServiceReference1.ChebiWebServicePortType.getAllOntologyChildrenInPathAsync(ServiceReference1.getAllOntologyChildrenInPathRequest request)
        {
            return base.Channel.getAllOntologyChildrenInPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getLiteEntityResponse1> getAllOntologyChildrenInPathAsync(ServiceReference1.getAllOntologyChildrenInPath getAllOntologyChildrenInPath)
        {
            ServiceReference1.getAllOntologyChildrenInPathRequest inValue = new ServiceReference1.getAllOntologyChildrenInPathRequest();
            inValue.getAllOntologyChildrenInPath = getAllOntologyChildrenInPath;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getAllOntologyChildrenInPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getStructureSearchResponse> ServiceReference1.ChebiWebServicePortType.getStructureSearchAsync(ServiceReference1.getStructureSearchRequest request)
        {
            return base.Channel.getStructureSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getStructureSearchResponse> getStructureSearchAsync(ServiceReference1.getStructureSearch getStructureSearch)
        {
            ServiceReference1.getStructureSearchRequest inValue = new ServiceReference1.getStructureSearchRequest();
            inValue.getStructureSearch = getStructureSearch;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getStructureSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getUpdatedPolymerResponse1> ServiceReference1.ChebiWebServicePortType.getUpdatedPolymerAsync(ServiceReference1.getUpdatedPolymerRequest request)
        {
            return base.Channel.getUpdatedPolymerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getUpdatedPolymerResponse1> getUpdatedPolymerAsync(ServiceReference1.getUpdatedPolymer getUpdatedPolymer)
        {
            ServiceReference1.getUpdatedPolymerRequest inValue = new ServiceReference1.getUpdatedPolymerRequest();
            inValue.getUpdatedPolymer = getUpdatedPolymer;
            return ((ServiceReference1.ChebiWebServicePortType)(this)).getUpdatedPolymerAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChebiWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChebiWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.ebi.ac.uk/webservices/chebi/2.0/webservice");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ChebiWebServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ChebiWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ChebiWebServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.ChebiWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ChebiWebServicePort,
        }
    }
}
